### ISSUE TITLE
Let's get some closure!

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/imagineering#1]
Sorry, Ivan, not that kind of clojure.

It would be super-fantastic to have a tool that could parse the HTML generated for modules, and alert us if we didn't close a tag within an id. Often, when we close a tag incorrectly, or just forget to close it at all, that page hums along merrily, and then wrecks havoc a page or two down. And then it's tricky to figure out where everything went wrong.

**Comment by ivanreese** [comment]
There are [quite](http://yeoman.io) a [few](http://gulpjs.com) wonderful [tools](http://gruntjs.com) for [ensuring](http://www.jslint.com) that [HTML](http://validator.w3.org), [CSS](http://jigsaw.w3.org/css-validator/), and [JS](http://jshint.com) are correct, well-formatted, and likely do what you want them to do. Most of these tools are designed to be used from the command line, so that the user has a lot of control over how to plug them together, like Lego. But, Unix is a bit of a tough sell for web designers who are used to working with GUI tools. Some of these tools are getting popular enough that people are making GUI wrappers around them — CodeKit was one of the first such tools to hit the market, but there are others now too.

When I get back from Europe, I will be looking more deeply into this space, and possibly finding an alternative to CodeKit for us to use. CodeKit is nice, but it has a very limited feature set, and you can't really "add your own tools" to it, the way you can with the command line tools.

**Comment by ivanreese** [comment]
https://developers.google.com/closure/

**Comment by ivanreese** [comment]
We could also integrate this sort of stuff into CodeKit with Hooks: http://incident57.com/codekit/help.html#hooks

It's worth mentioning that CodeKit 2.2 seems to be a vast improvement. Maybe CodeKit is a keeper after all!

**Comment by ivanreese** [comment]
This is a reminder for us to check out: http://jscs.info and http://eslint.org/

**Comment by ivanreese** [comment]
Further: https://atom.io/packages/atom-beautify

**Comment by ivanreese** [comment]
We're using Gulp now. We have compile-time errors for syntax, and this seems to be less of a daily pain. Of course, we'll try to find ever better solutions as time goes on.
